### ISSUE TITLE
Mythical Cape/Fremennik Boots (2 if that matters) swap not working

### ISSUE THREAD

**Issue by theprinnydood** [raiyni/menu-swapper-extended#103]
My plugin has the default setting as Wear for both the cape and boots, but my inventory says teleport (and clicking on them does teleport me, so it's not just a UI glitch). However, the Drakan's Medallion and Kharesdt's Memoirs/Book of the Dead swaps seem to be working just fine. I don't have the other options available to test, so there might be even more issues?

If there are any known conflicts with these items in particular, I'd be happy to learn about them; otherwise, I've just experienced this discrepancy today.

**Comment by theprinnydood** [comment]
Update: I parsed through some of the other issues and saw that the original MES can overwrite some of the settings of this plugin. Is there any way to change that?

**Comment by raiyni** [comment]
This is probably related to #15
