### ISSUE TITLE
Wilderness lever, Claim Dynamite, Obelisk and Construction cape not working

### ISSUE THREAD

**Issue by vitorebom** [raiyni/menu-swapper-extended#11]
They are not doing their intended behavior, decant is working as intended

**Comment by m0bilebtw** [comment]
Karamja gloves option also not swapping

**Comment by ChronHD** [comment]
Buy planks isnt working either

**Comment by Broooklyn** [comment]
It seems all the menu swaps stopped working with [1a3c804f](https://github.com/raiyni/menu-swapper-extended/commit/1a3c804f2034680b3ddbf7cc87f65a39b8f77b05).  

Running the test results in `java.lang.IllegalArgumentException: @Subscribed method "public void io.ryoung.menuswapperextended.MenuSwapperPlugin.onStartup()" must take exactly 1 argument`

Removing lines 82-95 allows the swaps to work again, but then "don't swap items with shift held" won't occur.

**Comment by raiyni** [comment]
Rip. I named the events wrong. There shouldn't be the on part
  

  

  

  
  
  
  
  
>

**Comment by raiyni** [comment]
This should work now once plugin hub builds.

Sorry for the troubles.
