### ISSUE TITLE
Suggest to add Slepe teleport to Drakan's medallion

### ISSUE THREAD

**Issue by michaljireht** [raiyni/menu-swapper-extended#111]
Swaps for Ver Sinhaza and Darkmeyer already exist, might be good to also add Slepe.

**Comment by raiyni** [comment]
Can you screenshot the the options please

**Comment by michaljireht** [comment]
![257768871_617972126063584_3468487811695001479_n](https://user-images.githubusercontent.com/43021338/142507127-2ad4b792-67a7-491c-a2bf-645e59403b16.jpg)

Here you go

**Comment by raiyni** [comment]
Thank you. I'll submit a PR for this tomorrow but I won't have membership to really test it but I don't think it will matter. 

🙏 

🙏 

🙏

**Comment by michaljireht** [comment]
Thank you!

**Comment by raiyni** [comment]
Merged in master
