### ISSUE TITLE
Interaction with Custom Left Click Drop plugin

### ISSUE THREAD

**Issue by joeamansfield** [raiyni/menu-swapper-extended#117]
For some reason, this plugin seems to interact with the Custom Left Click Drop plugin that is on the hub. When you enable one of them, both are enabled, and the same applies to disabling them. This is pretty annoying, since I would like to leave menu swapper on all the time, but only enable the other when I am actually using it.

**Comment by raiyni** [comment]
should be fixed

**Comment by joeamansfield** [comment]
seems to work properly now, thanks!
