### ISSUE TITLE
Add a Whitelist to revert the original MES on all but listed wanted items

### ISSUE THREAD

**Issue by vitorebom** [raiyni/menu-swapper-extended#15]
The original MES doesn't discriminiate between wearable teleport items when swapping

**Comment by vitorebom** [comment]
would this work to menu entry swap a given list of items?
`		else if (!shiftHeld && !getswapitems.equals("")
		{
			final String configSwapItems = config.getSwapItems().toLowerCase();
    			String[] ItemsSwapArray = new String[configSwapItems.size()];
     			ItemsSwapArray = configSwapItems.toArray(ItemsSwapArray);
			ItemsSwapArray.foreach((item) ->
					if  option.equals("wear"))
					{
					swap("rub", option, target, index);
					swap("teleport", option, target, index);
					}
					else if (option.equals("wield"))
					{
					swap("teleport", option, target, index);
					}	
			);
		}`

**Comment by raiyni** [comment]
this has been added in runelite master
