### ISSUE TITLE
Ability to swap "Charter to last destination" on Trader Crewmembers

### ISSUE THREAD

**Issue by Jaakkonen** [raiyni/menu-swapper-extended#18]
Chartering to last destination was added as a menu option in some recent QoL update. It'd be nice having this as the default option.

The name of that option does vary depending on the latest route but by default it's the 4th option and is of name "Charter-to <Last Destination>"

**Comment by Jaakkonen** [comment]
I made a pull request https://github.com/raiyni/menu-swapper-extended/pull/19 to fix this.

**Comment by raiyni** [comment]
Added in https://github.com/raiyni/menu-swapper-extended/commit/02e623fc3015c539453cb714fb17f6542307da8e
