### ISSUE TITLE
Remove the Clear All bank fillers 

### ISSUE THREAD

**Issue by ikagesoboi** [raiyni/menu-swapper-extended#34]
Hey,
I use bank fillers a lot to organize my bank.
Currently the default options when you left click bank fillers
pulls up this menu
![Annotation 2020-06-16 025927](https://user-images.githubusercontent.com/66999403/84760866-7b24bf00-af7d-11ea-95c6-66e2fcdd642f.png)
and if you accidentally hit clear all, 
my entire bank is wiped of any fillers i had.
It would be nice if i could either get a shift click to clear 1 bank filler,
or just have the clear all removed from my left click options.

Thanks!

**Comment by raiyni** [comment]
Sorry but I don't want to remove menu entries. Runelite has maintained a stance of not doing that, so I will too.

**Comment by ikagesoboi** [comment]
In that case are you able to make the "shift+left click" the "clear bank filler" option?
kind of like how you have the bank shift left click a specific option?
or would that not be possible.
