### ISSUE TITLE
Suggestion: Add left click "Check" seedbox

### ISSUE THREAD

**Issue by moedameyer** [raiyni/menu-swapper-extended#45]
Very useful for UIM and ironmen. More often you are checking what seeds are in the box rather than left click filling. With the recent "Open and Close" addition to the seed box, seeds will automatically enter the seedbox further making the "fill" option less useful.

**Comment by SomeZer0** [comment]
I opened a pull request for this a while back, https://github.com/raiyni/menu-swapper-extended/pull/29 should be what you wanted, yes?

**Comment by moedameyer** [comment]
Thanks, I didn't notice that at the time.
