### ISSUE TITLE
Construction Cape Issue

### ISSUE THREAD

**Issue by Brettgod1355** [raiyni/menu-swapper-extended#49]
With the runelite client's menu entry swapper teleport option turned on and your plugin setup so left clicking on the con cape I found an issue.

If you turn off any runelite plugin or go into the settings then back out of the setting of any plugin it reverts the left click option of the cons cape back to the normal MES option. The only way to change it back it to turn off then back on any plugin.

**Comment by raiyni** [comment]
I would consider this part of https://github.com/raiyni/menu-swapper-extended/issues/15
