### ISSUE TITLE
Karamja Gloves swapper overrides Shift-Click swap

### ISSUE THREAD

**Issue by hjdarnel** [raiyni/menu-swapper-extended#5]
This is my bad. #3 broke the shift click option on Karamja Gloves, so trying to configure shift-click on Karamja Gloves will always give the configured Menu Swap option from this plugin, even if shift-click is configured to a different menu option.

**Comment by raiyni** [comment]
I don't have members anymore to 100% a fix for this but I can try on a f2p item maybe. Reading the shift click config should be fine and exiting if that's matched.

**Comment by raiyni** [comment]
Fixed in 1a3c804
