### ISSUE TITLE
Adding a Pick-Lock/Swap to Dorgeshuun Rich Chests in the Menu Entry Swapper (Extended)

### ISSUE THREAD

**Issue by chadamantbar** [raiyni/menu-swapper-extended#55]
Adding a Pick-Lock/Swap to Dorgeshuun Rich Chests in the Menu Entry Swapper (Extended) would be convenient if it is allowed

**Comment by raiyni** [comment]
Not allowed per https://oldschool.runescape.wiki/w/Update:Another_Message_About_Unofficial_Clients
