### ISSUE TITLE
Suggestion: Individually selecting what left click does on teleport items

### ISSUE THREAD

**Issue by ablababla** [raiyni/menu-swapper-extended#58]
As it is right now, it's all or nothing.
When left clicking, I'd like certain items to retain their default "wear" action, while others, I'd want to "rub".

**Comment by raiyni** [comment]
Use custom shift click then. As is, I'm not adding any advanced features to this plugin until the state of this plugin being merged into master is more clear.

**Comment by ablababla** [comment]
That is my current solution, but I'm unsatisfied with it.
Here's hoping things get sorted out.
