### ISSUE TITLE
Issue with the Builder store swap not swapping correctly

### ISSUE THREAD

**Issue by oojava** [raiyni/menu-swapper-extended#6]
```java
else if (config.swapStore() && option.equals("trade-general-store"))
{
	swap("trade-builders-store", option, target, index);
}
```

This code doesnt work since the first option on the builder store is "Talk-to"
![image](https://user-images.githubusercontent.com/2854960/77309740-30234480-6ccb-11ea-87ab-2c0b12a2aac3.png)
(Normal Runelite menu entry swapper doesn't change this)

This swap should be moved up to the "Talk-to" section. 

If you want I can make this change sometime this week but its small and simple enough I figured it was easier to just report here. Vs. me writing it and us both testing it. 

Anyways thanks for the amazing plugin and best of luck mate!

**Comment by raiyni** [comment]
You can make the change if you want, I don't have members to test this anymore

**Comment by raiyni** [comment]
Added in fae601d
