### ISSUE TITLE
Pharaoh's Sceptre left-click teleports

### ISSUE THREAD

**Issue by sarcophaguy** [raiyni/menu-swapper-extended#61]
Jagex somewhat recently changed the left-click option on the Pharaoh's sceptre to 'wield' in an attempt to crack down on lures that involve this item. This made training Thieving through Pyramid Plunder slightly more tedious by requiring more inputs. This plugin has a feature that's supposed to let you toggle the left-click option on the sceptre, but it doesn't seem to work, probably due to this default change from 'teleport' to 'wield'. Would be rad if someone made the entry swapper actually work on the Pharaoh's sceptre again.

**Comment by Broooklyn** [comment]
Fixed in 4857cc4285a1ff15ac21ad902eb966797cdf7d22
