### ISSUE TITLE
Suggestion: Shift-click compass Look Direction

### ISSUE THREAD

**Issue by Spookytheboy** [raiyni/menu-swapper-extended#69]
There is a right-click dropdown on game compass with options:
- Look North
- Look South
- Look East
- Look West

I haven't seen any customization available for shift-clicking this compass, which is something I find myself clicking quite often depending on the content. Personally it would be great to be able to shift-click "Look South" but adding a dropdown option to customize the shift click would also make sense.

**Comment by raiyni** [comment]
This is better suited for main client
