### ISSUE TITLE
Suggestion: Add mythical cape

### ISSUE THREAD

**Issue by Tolemi959** [raiyni/menu-swapper-extended#77]
And by mythical cape I mean the cape itself, not the rack. I use the mythical cape for things like KQ and Corp, but the first option is teleport because of the normal menu entry swapper (not extended), which I would love to keep enabled for quick teleporting with jewelry etc. Any chance to get this added?

**Comment by raiyni** [comment]
This is fine, it would require someone with a mythical cape to work on it or someone with a mythical cape to provide menu options

**Comment by Tolemi959** [comment]
Nice! I don't really know how to program stuff, so is there a guide on it I can use somewhere? And the mythical cape options are as follows (default, no menu entry swapper teleport item enabled):
-  Wear
-  Teleport
-  Use
-  Drop
-  Examine
-  Cancel

The menu entry swapper swaps wear and teleport if enabled.
