### ISSUE TITLE
Rantz Collect Swaps Banker to Collect

### ISSUE THREAD

**Issue by TheLawGiver** [raiyni/menu-swapper-extended#94]
Hello there! I absolutely love the menu swapped extended - thank you for your time in creating it! I wanted to give you a quick heads up that I recently selected the Rantz Collect feature and it actually changed every banker to prioritize collect instead of bank despite me having bank selected on the menu entry swapper regular tool. I have attached examples of the difference between it being on and off. For reference, it has changed ALL of my bankers in the game.
![Rantz Collect Off](https://user-images.githubusercontent.com/87867824/126801537-d9185908-e9a5-43ea-8604-17242cc898ed.png)
![Rantz Collect On](https://user-images.githubusercontent.com/87867824/126801540-7f6d8b8a-10c4-4e7b-945b-206001d782ec.png)

**Comment by raiyni** [comment]
This should be fixed now that rantz has his option renamed
