### ISSUE TITLE
Menu Entry Swapper Extended > Item Swaps > Cast Bloom --- "Blisterwood Flail"

### ISSUE THREAD

**Issue by jameseriches** [raiyni/menu-swapper-extended#98]
The plugin option to have "cast bloom" enabled applies to all sickles but does not seem to be working for the Blisterwood Flail. 
![image](https://user-images.githubusercontent.com/65311783/131950329-2bbdcc66-31b4-4f2b-88dc-c8cf9eb4724d.png)
![image](https://user-images.githubusercontent.com/65311783/131950350-0a012e17-8c75-4486-8b52-967cf4c6acc6.png)

**Comment by raiyni** [comment]
Merged
